# Generated by Django 5.2.17 on 2026-09-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0033_remove_issue_issue_list_muted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turningpoint',
            name='kind',
            field=models.IntegerField(choices=[(1, 'First seen'), (2, 'Resolved'), (3, 'Muted'), (4, 'Marked as regressed'), (5, 'Unmuted'), (6, 'Reopened'), (10, 'Release info added'), (20, 'Merged'), (100, 'Manual annotation')]),
        ),
    ]
