# Generated by Django 5.2.17 on 2026-09-02 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0034_alter_turningpoint_kind_merged'),
        ('projects', '0019_alter_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='metadata',
            field=models.TextField(default='{}'),
        ),
        migrations.CreateModel(
            name='ExternalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='github', max_length=64)),
                ('external_project', models.CharField(blank=True, default='', max_length=256)),
                ('identifier', models.CharField(max_length=256)),
                ('web_url', models.URLField(max_length=1024)),
                ('display_name', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='external_issues', to='issues.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.project')),
            ],
            options={
                'ordering': ['provider', 'identifier'],
                'unique_together': {('issue', 'provider', 'identifier')},
            },
        ),
    ]
